data_path: "/Volumes/Jay_4TB/data/LC_Quad/"

data:
  init_train_data: "{{ data_path }}train.csv"
  init_test_data: "{{ data_path }}test.csv"
  base_train_data: "{{ data_path }}base_train.csv"
  base_test_data: "{{ data_path }}base_test.csv"
  lcquad_token: "{{ data_path }}lcquad_token.json"
  modf_train_data: "{{ data_path }}modf_train_data.csv"
  modf_valid_data: "{{ data_path }}modf_valid_data.csv"
  modf_test_data: "{{ data_path }}modf_test_data.csv"
  clm_train_dataset: "{{ data_path }}train_clm_dataset.pt"
  sft_train_dataset: "{{ data_path }}train_sft_dataset.pt"
  sft_val_dataset: "{{ data_path }}valid_sft_dataset.pt"
  sft_test_dataset: "{{ data_path }}test_sft_dataset.pt"
  sft_train_result_data: "{{ data_path }}train_sft_result_data.csv"
  sft_val_result_data: "{{ data_path }}valid_sft_result_data.csv"
  sft_test_result_data: "{{ data_path }}test_sft_result_data.csv"
  rm_train_data: "{{ data_path }}train_rm_data.csv"
  rm_val_data: "{{ data_path }}valid_rm_data.csv"
  rm_test_data: "{{ data_path }}test_rm_data.csv"
  rm_train_with_reward_score_data: "{{ data_path }}train_rm_with_reward_score_data.csv"
  rm_val_with_reward_score_data: "{{ data_path }}valid_rm_with_reward_score_data.csv"
  rm_test_with_reward_score_data: "{{ data_path }}test_rm_with_reward_score_data.csv"
  rm_train_with_reward_score_dataset: "{{ data_path }}train_rm_with_reward_score_dataset.pt"
  rm_val_with_reward_score_dataset: "{{ data_path }}valid_rm_with_reward_score_dataset.pt"
  rm_test_with_reward_score_dataset: "{{ data_path }}test_rm_with_reward_score_dataset.pt"
  rlhf_train_dataset: "{{ data_path }}train_rlhf_dataset.pt"
  inf_test_dataset: "{{ data_path }}test_inf_dataset.pt"
  inf_result_data: "{{ data_path }}lcquad_result_data.csv"
  inf_result_analysis_data: "{{ data_path }}lcquad_result_analysis_data.csv"
  inf_result_scores: "{{ data_path }}lcquad_result_scores.txt"