model_path: "/Volumes/Jay_4TB/model_utils/models/LC_Quad/"

# gpt2-xl (no LORA)
# Qwen/Qwen2.5-1.5B (no LORA) ~ X , complete failure - 02022026
# mistralai/Mistral-7B-v0.1 (LORA)
# google/gemma-2-9b (LORA)
# meta-llama/Llama-2-7b-hf (LORA)

model:
  device: "cpu"
  dtype: null
  chosen_model: "gpt2-xl"
  tokenizer: "gpt2-xl"
  tokenizer_path: "{{ model_path }}lcquad_tokenizer_{model_ind}"
  base_model_path: "{{ model_path }}base_model_{model_ind}"
  clm_model:
    clm_model_path: "{{ model_path }}lcquad_clm_model_{model_ind}/{model_version}"
    model_config:
      num_train_epochs: 10
  sft_model:
    sft_model_path: "{{ model_path }}lcquad_sft_model_{model_ind}/{model_version}"
    num_workers: 0
    model_config:
      allowed_max_length: 1024
      ignore_index: -100
      batch_size:
        effective_batch_size: 32
        train_batch_size: 4
        test_batch_size: 4
        val_batch_size: 4
      num_epochs: 10
      epoch_eval_freq: 2
  rm_model:
    rm_model_path: "{{ model_path }}lcquad_rm_model_{model_ind}/{model_version}"
    num_workers: 0
    model_config:
      allowed_max_length: 1024
      ignore_index: -100
      batch_size:
        effective_batch_size: 32
        train_batch_size: 8
        test_batch_size: 4
        val_batch_size: 4
      num_epochs: 10
      epoch_eval_freq: 2
  rlhf_model:
    rlhf_model_path: "{{ model_path }}lcquad_rlhf_model_{model_ind}/{model_version}"
    num_workers: 0
    model_config:
      allowed_max_length: 1024
      allowed_tokens: 64
      ignore_index: -100
      batch_size:
        effective_batch_size: 32
        train_batch_size: 8
        test_batch_size: 4
        val_batch_size: 4
      num_epochs: 10
  inf_model:
    inf_model_path: "{{ model_path }}lcquad_inf_model_{model_ind}/{model_version}"
    num_workers: 0
    model_config:
      allowed_max_length: 1024
      allowed_tokens: 64
      ignore_index: -100
      batch_size:
        test_batch_size: 4