model_path: "/Volumes/Jay_4TB/model_utils/models/LC_Quad/"

model:
  device: "cpu"
  chosen_model: "Qwen/Qwen2.5-1.5B"
  tokenizer: "Qwen/Qwen2.5-1.5B"
  tokenizer_path: "{{ model_path }}lcquad_tokenizer_{model_ind}"
  base_model_path: "{{ model_path }}base_model_{model_ind}"
  clm_model:
    clm_model_path: "{{ model_path }}lcquad_clm_model_{model_ind}/{model_version}"
    model_config:
      num_train_epochs: 100
      learning_rate: 2e-5
      weight_decay: 0.01
  sft_model:
    sft_model_path: "{{ model_path }}lcquad_sft_model_{model_ind}/{model_version}"
    num_workers: 0
    model_config:
      allowed_max_length: 1024
      ignore_index: -100
      batch_size:
        effective_batch_size: 32
        train_batch_size: 8
        test_batch_size: 4
        val_batch_size: 4
      num_epochs: 10
      epoch_eval_freq: 2
  rm_model:
    rm_model_path: "{{ model_path }}lcquad_rm_model_{model_ind}/{model_version}"
    num_workers: 0
    model_config:
      allowed_max_length: 1024
      ignore_index: -100
      batch_size:
        effective_batch_size: 32
        train_batch_size: 8
        test_batch_size: 4
        val_batch_size: 4
      num_epochs: 10
      epoch_eval_freq: 2
  rlhf_model:
    rlhf_model_path: "{{ model_path }}lcquad_rlhf_model_{model_ind}/{model_version}"
    num_workers: 0
    model_config:
      allowed_max_length: 1024
      allowed_tokens: 64
      ignore_index: -100
      batch_size:
        effective_batch_size: 32
        train_batch_size: 8
        test_batch_size: 4
        val_batch_size: 4
      num_epochs: 10
  inf_model:
    inf_model_path: "{{ model_path }}lcquad_inf_model_{model_ind}/{model_version}"
    num_workers: 0
    model_config:
      allowed_max_length: 1024
      allowed_tokens: 64
      ignore_index: -100
      batch_size:
        test_batch_size: 4